ARG NODE_VERSION=24
FROM ghcr.io/tweedegolf/node:${NODE_VERSION}-extended

RUN apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
        chromium \
        firefox-esr \
        x11-utils \
        xvfb \
        dbus \
        udev \
        fluxbox \
        procps \
        tzdata \
        libosmesa6 \
        libglapi-mesa \
        libgl1-mesa-dri \
        mesa-utils \
    && rm -rf /var/lib/apt/lists/*
