ARG NODE_VERSION
FROM ghcr.io/tweedegolf/node:${NODE_VERSION}

# Install dependencies for extended install
RUN apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
        ghostscript \
        python3 \
        python3-dev \
        python3-pip \
        python3-venv \
        gconf-service \
        libasound2 \
        libatk1.0-0 \
        libc6 \
        libcairo2 \
        libcups2 \
        libdbus-1-3 \
        libexpat1 \
        libfontconfig1 \
        libgbm-dev \
        libgcc1 \
        libgconf-2-4 \
        libgdk-pixbuf2.0-0 \
        libglib2.0-0 \
        libgtk-3-0 \
        libnspr4 \
        libpango-1.0-0 \
        libpangocairo-1.0-0 \
        libstdc++6 \
        libx11-6 \
        libx11-xcb1 \
        libxcb1 \
        libxcomposite1 \
        libxcursor1 \
        libxdamage1 \
        libxext6 \
        libxfixes3 \
        libxi6 \
        libxrandr2 \
        libxrender1 \
        libxshmfence-dev \
        libxss1 \
        libxtst6 \
        fonts-liberation \
        fonts-freefont-ttf \
        libayatana-appindicator1 \
        libnss3 \
        xdg-utils \
        libdrm2 \
    && rm -rf /var/lib/apt/lists/*
