name: Docker

on:
  workflow_call:

jobs:
  build:
    strategy:
      matrix:
        include:
          - node_version: 24
            latest: true
            lts: true
            debian: trixie
            postgresql: 18
          - node_version: 22
            latest: false
            lts: false
            debian: bookworm
            postgresql: 17
          - node_version: 20
            latest: false
            lts: false
            debian: bookworm
            postgresql: 17
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Build the base image
        uses: tweedegolf/build-container-image@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          push: ${{ github.ref == 'refs/heads/main' }}
          platforms: "linux/amd64,linux/arm64"
          build-args: |
            DEBIAN_VERSION=${{ matrix.debian }}
            NODE_VERSION=${{ matrix.node_version }}
            POSTGRESQL_VERSION=${{ matrix.postgresql }}
          tags: |
            ghcr.io/tweedegolf/node:${{matrix.node_version}}
            ${{ matrix.latest && 'ghcr.io/tweedegolf/node:latest' || '' }}
            ${{ matrix.lts && 'ghcr.io/tweedegolf/node:lts' || '' }}

      - name: Build the extended image
        uses: tweedegolf/build-container-image@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          file: Dockerfile-extended-${{ matrix.debian }}
          push: ${{ github.ref == 'refs/heads/main' }}
          platforms: "linux/amd64,linux/arm64"
          build-args: |
            DEBIAN_VERSION=${{ matrix.debian }}
            NODE_VERSION=${{ matrix.node_version }}
          tags: |
            ghcr.io/tweedegolf/node:${{matrix.node_version}}-extended
            ${{ matrix.latest && 'ghcr.io/tweedegolf/node:latest-extended' || '' }}
            ${{ matrix.lts && 'ghcr.io/tweedegolf/node:lts-extended' || '' }}

      - name: Build the full image
        uses: tweedegolf/build-container-image@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          file: Dockerfile-full
          push: ${{ github.ref == 'refs/heads/main' }}
          platforms: "linux/amd64,linux/arm64"
          build-args: |
            DEBIAN_VERSION=${{ matrix.debian }}
            NODE_VERSION=${{ matrix.node_version }}
          tags: |
            ghcr.io/tweedegolf/node:${{matrix.node_version}}-full
            ${{ matrix.latest && 'ghcr.io/tweedegolf/node:latest-full' || '' }}
            ${{ matrix.lts && 'ghcr.io/tweedegolf/node:lts-full' || '' }}
