name: Docker

on:
  workflow_call:

jobs:
  build:
    strategy:
      matrix:
        include:
          - node_version: 22
            latest: true
            lts: true
          - node_version: 20
            latest: false
            lts: false
          - node_version: 18
            latest: false
            lts: false
    env:
      debian_version: bookworm
      postgresql_version: 17
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Build the base image
        uses: tweedegolf/build-container-image@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          push: ${{ github.ref == 'refs/heads/main' }}
          platforms: "linux/amd64,linux/arm64"
          build-args: |
            DEBIAN_VERSION=${{ env.debian_version }}
            NODE_VERSION=${{ matrix.node_version }}
            POSTGRESQL_VERSION=${{ env.postgresql_version }}
          tags: |
            ghcr.io/tweedegolf/node:${{matrix.node_version}}
            ${{ matrix.latest && 'ghcr.io/tweedegolf/node:latest' || '' }}
            ${{ matrix.lts && 'ghcr.io/tweedegolf/node:lts' || '' }}

      - name: Build the extended image
        uses: tweedegolf/build-container-image@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          file: Dockerfile-extended
          push: ${{ github.ref == 'refs/heads/main' }}
          platforms: "linux/amd64,linux/arm64"
          build-args: |
            DEBIAN_VERSION=${{ env.debian_version }}
            NODE_VERSION=${{ matrix.node_version }}
          tags: |
            ghcr.io/tweedegolf/node:${{matrix.node_version}}-extended
            ${{ matrix.latest && 'ghcr.io/tweedegolf/node:latest-extended' || '' }}
            ${{ matrix.lts && 'ghcr.io/tweedegolf/node:lts-extended' || '' }}

      - name: Build the full image
        uses: tweedegolf/build-container-image@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          file: Dockerfile-full
          push: ${{ github.ref == 'refs/heads/main' }}
          platforms: "linux/amd64,linux/arm64"
          build-args: |
            DEBIAN_VERSION=${{ env.debian_version }}
            NODE_VERSION=${{ matrix.node_version }}
          tags: |
            ghcr.io/tweedegolf/node:${{matrix.node_version}}-full
            ${{ matrix.latest && 'ghcr.io/tweedegolf/node:latest-full' || '' }}
            ${{ matrix.lts && 'ghcr.io/tweedegolf/node:lts-full' || '' }}
